# Usamos una imagen ligera de Python
FROM python:3.11-slim

# Evitamos que Python genere archivos .pyc y permite ver logs en tiempo real
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos primero solo los requerimientos para aprovechar la caché de Docker
COPY app/requirements.txt .

# Instalamos las dependencias (Flask )
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto de la aplicación
COPY app/ .

# Exponemos el puerto que definiste en app.py
EXPOSE 5000

# Comando para arrancar la aplicación
CMD ["python", "app.py"]